import { Text } from "@react-pdf/renderer";
import { letterStyles } from "@/components/pdf/letterStyles";

export function Form16PartBDisclaimer({ orgName }: { orgName: string }) {
  return (
    <>
      <Text style={letterStyles.footer}>
        This is Form 16 – Part B ONLY (the salary and tax computation annexure), generated by{" "}
        {orgName}&apos;s payroll system. It is NOT a substitute for Form 16 Part A, which is a TDS
        certificate that by law can only be issued through the Income Tax Department&apos;s TRACES
        portal and carries a unique certificate number and digital signature that no third-party
        software can produce. {orgName} must separately download Part A from TRACES and attach it to
        this Part B before issuing a complete Form 16 to the employee.
      </Text>
      <Text style={letterStyles.footer}>
        Figures above are computed from payroll records and the employee&apos;s tax declaration for
        this financial year. They are estimates for {orgName} and its chartered accountant to verify —
        not a filed tax return or an NSDL/TRACES-validated figure.
      </Text>
    </>
  );
}
