import Link from "next/link";

export function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="border-t border-slate-200 bg-white">
      <div className="mx-auto max-w-6xl px-4 py-6 text-sm text-slate-500">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <span className="font-semibold text-slate-700">TimHr</span>
          <div className="flex gap-4">
            <Link href="/privacy-policy" className="hover:text-slate-700 hover:underline">
              Privacy Policy
            </Link>
            <Link href="/terms" className="hover:text-slate-700 hover:underline">
              Terms &amp; Conditions
            </Link>
          </div>
        </div>
        <p className="mt-3 text-xs text-slate-400">
          Please consult your Chartered Accountant or another responsible person before finalizing any
          payroll, statutory filing, or HR document generated by this app. TimHr is not responsible for
          any errors, omissions, or non-compliance arising from its use.
        </p>
        <p className="mt-2 text-xs text-slate-400">© {year} TimHr. All rights reserved.</p>
      </div>
    </footer>
  );
}
