import Link from "next/link";
import { Card } from "@/components/ui/Card";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-6 p-4 py-10">
      <div>
        <Link href="/login" className="text-sm font-semibold text-blue-700 hover:underline">
          ← Back
        </Link>
      </div>

      <Card>
        <h1 className="mb-2 text-2xl font-bold text-slate-900">Terms &amp; Conditions</h1>
        <p className="mb-6 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-700">
          This is a template terms of service, not legal advice. Have it reviewed by a lawyer before
          relying on it as your company&apos;s actual terms.
        </p>

        <div className="space-y-5 text-sm leading-relaxed text-slate-700">
          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">1. The service</h2>
            <p>
              TimHr is a payroll and HR administration tool for small and medium businesses. It helps
              compute payroll, statutory deductions (PF, ESI, Professional Tax, TDS), and generate
              payslips, HR letters, and compliance summary reports.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">2. Not a substitute for professional advice</h2>
            <p>
              All statutory calculations, letters, and reports generated by TimHr are computed estimates
              based on the information entered by your company, and are provided for convenience only.
              They are <span className="font-semibold">not</span> a substitute for the judgment of a
              qualified Chartered Accountant, tax professional, or legal counsel. You are responsible for
              verifying all figures, filings, and documents before relying on them, issuing them to
              employees, or submitting them to any government authority. TimHr and its provider assume no
              liability for any errors, omissions, penalties, or non-compliance arising from use of this
              app, including but not limited to incorrect statutory deductions, missed filing deadlines,
              or documents issued without proper review.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">3. Your account</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for
              all activity under your account. You must ensure the accuracy of the data your company
              enters, since every calculation and document this app produces depends on it.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">4. Subscription and fees</h2>
            <p>[Subscription terms, billing cycle, and cancellation policy — add here.]</p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">5. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, TimHr and its provider shall not be liable for any
              indirect, incidental, special, or consequential damages, or for any loss of profits,
              revenue, data, or statutory penalties, arising out of or in connection with the use of this
              app.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">6. Termination</h2>
            <p>
              Either party may terminate use of the service at any time. Upon termination, your
              company&apos;s data will be handled in accordance with our{" "}
              <Link href="/privacy-policy" className="font-semibold text-blue-700 hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">7. Governing law</h2>
            <p>These terms are governed by the laws of [Governing State/Country — add here].</p>
          </section>

          <section>
            <h2 className="mb-1 text-base font-bold text-slate-900">8. Changes to these terms</h2>
            <p>
              These terms may be updated from time to time. Continued use of the app after an update
              constitutes acceptance of the revised terms.
            </p>
          </section>
        </div>
      </Card>
    </div>
  );
}
